### ISSUE TITLE
ASReview test

### ISSUE THREAD

**Issue by thin-lizard** [PugetSoundClinic-PIT/Fare-Fair#12]
I tested out ASReview for screening - I think its easy to use, but my main complaint is that you can't skip around between papers. Its nice to have each abstract presented...but I'm also not opposed to reading the abstract out of a spreadsheet.  

- i dont think that what we export from ASReview matches what we're able to export directly from W0S - we lose a lot of the fields we selected when exporting from W0S - like usage counts, funding info, open access
    - [this was exported directly from WoS](https://docs.google.com/spreadsheets/d/11DN9SWK55juCsTrrwOBeqUnlveDQNBBhg131OPnUo8k/edit#gid=1011390885)
    - [this is after screening and exporting from ASReview](https://docs.google.com/spreadsheets/d/1B7ny24YC4p1YnuDV0NPFPDux4K82evAWEeY2HfFzeEo/edit#gid=326701076)
- We also seem to lose these fields when we export a CSV file from zotero -- I tested this with both the .ris file of WoS results and the ris file of papers screened through ASReview (ie importing the .ris file _into_ zotero then exporting from zotero as a CSV)

**Comment by samMint** [comment]
Lindsey, I also had issues in the import/export workflow between WoS, Zotero, Sheets, and ASReview. I only retained all fields when I tried exporting WoS results as .xls and then imported them to Sheets (i.e. skipping Zotero). Maybe there’s an easy fix to preserve everything when exporting the .ris? I’ll troubleshoot more this week.

I like ASReview! The analytics could be useful, and I find it a bit easier to focus when the abstracts are presented one at a time. ASReview also adds a wrinkle to the methodology we're using, which I think could be nice to think about down the line. Since my sample was so small, it's hard to say how effective ASReview will be for sticking irrelevant results at the bottom of the pile, but it could speed things up for us.

Here are my (very artificial) results. I didn't have any irrelevant records, so I just chose one as irrelevant in order to proceed. I also didn't add a methodology variable yet. 

https://docs.google.com/spreadsheets/d/1-ndUD1NLcr2Tkw3ICmU3h3vCtV0L83mrFp3GZPI7QJs/edit?usp=sharing
